language: node_js
node_js:
- "8"
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: 142.93.124.203
branches:
  only:
  - travis
before_install:
- openssl aes-256-cbc -K $encrypted_2fcef3a7a419_key -iv $encrypted_2fcef3a7a419_iv
  -in .travis/travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa
after_success:
- bash .travis/deploy.sh